### PR TITLE
fixed overflow bug of sys:generate_collective, int tmp -> int64_t tmp

### PR DESCRIPTION
**Pull request by changhai0109**
Fixed an overflow bug in sys:generate_collective
The tmp variable in type int, might overflow when has comm_size > 2GB, and that is possible in transformer traces.

Without fixing bug, the tick might be a really high number, while sometimes the simulation will stop before finished.

modified:   astra-sim/system/Sys.cc

### CODE REVIEW

**Comment by TaekyungHeo** [comment]
Can we use uint64_t instead because chunk_size will be assigned to tmp?

**Comment by changhai0109** [comment]
> Can we use uint64_t instead because chunk_size will be assigned to tmp?

My answer is: yes, but using int64_t may be safer.

The reason is that the original type is int. Without knowing the reason, I prefer it is still a signed type after changing, as its name is tmp, but not something like chunk_size. So maybe it is just intended to be as a tmp variable and may be re-used other than on chunk size in other versions. Also, int64_t is large enough and I think assigning uint64_t to int64_t is always safe as long as it is less than 2^63.

This is just my opinion, and very very probably my concern will not really happen, If uint64_t is less confusing to people, just change it.

**Comment by TaekyungHeo** [comment]
If it is better to use uint64_t, could you please update this PR to use uint64_t?

**Comment by changhai0109** [comment]
Changed to uint64_t, also changed name to "remain_size" to avoid possible confusions.

**Comment by TaekyungHeo** [comment]
Perfect, thanks!

**Pull request merged**
