### PR TITLE
Update submodule version for Chakra to the lastest

### PR DESCRIPTION
**Pull request by JoongunPark**
## Summary
ASTRA-Sim currently uses an outdated version of Chakra as its external module, resulting in improper support for newer Chakra traces.

Two specific issues have been identified:

1. Chakra does not encode involved_dim in the trace, but ASTRA-Sim requires it.
2. The `is_cpu_op()` method in the ET feeder node always returns '0' after Chakra's schema update ([This commit](https://github.com/mlcommons/chakra/pull/114/files) from Chakra Repo).

This PR addresses these issues by:

1. Updating the submodule version for Chakra to the latest (July 17th).
2. Updating the include paths according to the latest Chakra structure.
3. Ensuring that involved_dim always includes all GPU nodes.

## Test Plan

Resnet-50 (newly collected)
[resnet-50.zip](https://github.com/user-attachments/files/16150388/resnet-50.zip)

```
Batch 16
./build/astra_analytical/build/bin/AstraSim_Analytical_Congestion_Unaware --workload-configuration=/home/un-gpu/Project/jpark/astra-sim/resnet-50/result-batch16/rank --system-configuration=./inputs/system/Ring.json --network-configuration=./inputs/network/analytical/Ring.yml --remote-memory-configuration=./inputs/remote_memory/analytical/no_memory_expansion.json

Batch 32
./build/astra_analytical/build/bin/AstraSim_Analytical_Congestion_Unaware --workload-configuration=/home/un-gpu/Project/jpark/astra-sim/resnet-50/result-batch32/rank --system-configuration=./inputs/system/Ring.json --network-configuration=./inputs/network/analytical/Ring.yml --remote-memory-configuration=./inputs/remote_memory/analytical/no_memory_expansion.json

Batch 64
./build/astra_analytical/build/bin/AstraSim_Analytical_Congestion_Unaware --workload-configuration=/home/un-gpu/Project/jpark/astra-sim/resnet-50/result-batch64/rank --system-configuration=./inputs/system/Ring.json --network-configuration=./inputs/network/analytical/Ring.yml --remote-memory-configuration=./inputs/remote_memory/analytical/no_memory_expansion.json
```

inputs/network/analytical/Ring.ym

```
 # 64 NPUs
 npus_count: [ 2 ]  # number of NPUs
```

Result
```
ring of node 0, id: 0 dimension: local total nodes in ring: 2 index in ring: 0 offset: 1total nodes in ring: 2
ring of node 0, id: 0 dimension: local total nodes in ring: 2 index in ring: 0 offset: 1total nodes in ring: 2
ring of node 0, id: 0 dimension: local total nodes in ring: 2 index in ring: 0 offset: 1total nodes in ring: 2
ring of node 0, id: 0 dimension: local total nodes in ring: 2 index in ring: 0 offset: 1total nodes in ring: 2
sys[0] finished, 297912000 cycles
sys[1] finished, 305405000 cycles

ring of node 0, id: 0 dimension: local total nodes in ring: 2 index in ring: 0 offset: 1total nodes in ring: 2
ring of node 0, id: 0 dimension: local total nodes in ring: 2 index in ring: 0 offset: 1total nodes in ring: 2
ring of node 0, id: 0 dimension: local total nodes in ring: 2 index in ring: 0 offset: 1total nodes in ring: 2
ring of node 0, id: 0 dimension: local total nodes in ring: 2 index in ring: 0 offset: 1total nodes in ring: 2
sys[1] finished, 570182000 cycles
sys[0] finished, 571099000 cycles

ring of node 0, id: 0 dimension: local total nodes in ring: 2 index in ring: 0 offset: 1total nodes in ring: 2
ring of node 0, id: 0 dimension: local total nodes in ring: 2 index in ring: 0 offset: 1total nodes in ring: 2
ring of node 0, id: 0 dimension: local total nodes in ring: 2 index in ring: 0 offset: 1total nodes in ring: 2
ring of node 0, id: 0 dimension: local total nodes in ring: 2 index in ring: 0 offset: 1total nodes in ring: 2
sys[1] finished, 1102981000 cycles
sys[0] finished, 1105115000 cycles
```

Following this PR (https://github.com/astra-sim/astra-sim/pull/196), I have updated cleanup code in build.sh

```
./build/astra_analytical/build.sh -l
```

### CODE REVIEW

**Comment by jinsun-yoo** [comment]
One more: Do you know the history behind changing how attribute values are fed in et_feeder? 
For example, for the attribute `comm_size`, we used to be able to feed all the values regardless of whether attr.value was uint64 or int64, or int32, etc ([link](https://github.com/mlcommons/chakra/blob/7a5faa80b22c002cb2fdf9b1c0d38d853df4c4bf/et_feeder/et_feeder_node.cpp#L70)). But now, if the value is not a type int64, et_feeder will feed in a value of 0 ([link](https://github.com/mlcommons/chakra/blob/d5c68023eac8147bad3c9bda8a8d93545b8961fa/src/feeder/et_feeder_node.cpp#L28))
I'm not sure what the python profiler uses, but both the et_generator and SGT uses type uint64. 
The key takeaway is that unless we have a way to force all trace producing tools to use uint64 for comm_size, this will be a problem.

**Comment by jinsun-yoo** [comment]
Split this item into a new comment: 

Unfortunately, with 2D, 3D communication, involved_dim needs to be [True, True] or [True, True, True], instead of just [True]. This current fix will only result in a 1D communication. I'll have to think of a way to go around this.

**Comment by JoongunPark** [comment]
Hi, 
1. 

> Hi @JoongunPark , thanks for the update!
> 
> 1. I editited your PR description to include the commit link where the is_cpu_op schema has been updated.
> 2. Did you make any changes in the codebase to address the issue No.2 in the PR description? (issue of is_cpu_op always returning 0)
> 3. Maybe this belongs to a separate thread. Do you think et_feeder_node.cpp should not set is_cpu_op to 1 as default? ([here](https://github.com/mlcommons/chakra/blob/d5c68023eac8147bad3c9bda8a8d93545b8961fa/src/feeder/et_feeder_node.cpp#L11)) As far as I can see, with the curren state, et_feeder will always force is_cpu_op to 1  ([link](https://github.com/astra-sim/astra-sim/blob/master/astra-sim/workload/Workload.cc#L128)). Even if the Chakra node is a COMM node, if is_cpu_op is set to 1, astra-sim's workload layer will treat this as a COMP node. Traces created through pytorch converter is okay, but those created with other tools (MSCCL->Chakra, SGT, etc.) need to continuously mark is_cpu_op to 0 .
> 4. One quick fix to the above item could be to adjust the order of if statements in Workload.cc so that comm comes before comp.

1. Thanks for the update!
2. Yes. The error stems from different type between trace ETFeeder. Updating ETFeeder will solve the problem.
3. Semntaically 'Comm' should not be is_cpu_op=true . You can check it here that only gpu_op can be COMM nodes (https://github.com/mlcommons/chakra/blob/d5c68023eac8147bad3c9bda8a8d93545b8961fa/src/converter/pytorch_converter.py#L329).
4. I haven't seen such case yet. As we can see in the 3. That should not happen. I prefer to report that as a bug to Chakra and fix that if that happens.

**Comment by JoongunPark** [comment]
> One more: Do you know the history behind changing how attribute values are fed in et_feeder? For example, for the attribute `comm_size`, we used to be able to feed all the values regardless of whether attr.value was uint64 or int64, or int32, etc ([link](https://github.com/mlcommons/chakra/blob/7a5faa80b22c002cb2fdf9b1c0d38d853df4c4bf/et_feeder/et_feeder_node.cpp#L70)). But now, if the value is not a type int64, et_feeder will feed in a value of 0 ([link](https://github.com/mlcommons/chakra/blob/d5c68023eac8147bad3c9bda8a8d93545b8961fa/src/feeder/et_feeder_node.cpp#L28)) I'm not sure what the python profiler uses, but both the et_generator ([link](https://github.com/mlcommons/chakra/blob/d5c68023eac8147bad3c9bda8a8d93545b8961fa/src/generator/generator.py#L194)) and SGT ([link](https://github.com/changhai0109/symbolic_tensor_network/blob/IOInfoEncoding/symbolic_tensor_graph/chakra/backends/chakra_00_4_backend/chakra_00_4_backend.py#L98)) uses type uint64. The key takeaway is that unless we have a way to force all trace producing tools to use uint64 for comm_size, this will be a problem.

Yes. That is the similar problem that I mentioned with is_cpu_op(). The root cause is strong typing in ETFeeder. In order to fix this, we can update schema in Chakra or some additional logic that enforce operations to have expected type. One immediate solution is giving the expected data type from other upstream projects (MSCCL->Chakra, SGT, etc.).

**Comment by JoongunPark** [comment]
> Split this item into a new comment:
> 
> Unfortunately, with 2D, 3D communication, involved_dim needs to be [True, True] or [True, True, True], instead of just [True]. This current fix will only result in a 1D communication. I'll have to think of a way to go around this.

I think this is really good point. Using involved_dim=[true] doesn’t make sense in those cases. 
We may consider providing users with the option to choose either involved_dim or ProcessGroup until we fully implement PG support in ASTRA-Sim.

**Comment by jinsun-yoo** [comment]
Just checked, LGTM!

**Comment by jinsun-yoo** [comment]
Leaving behind a bit of summarized history for the history diggers: 

1. ET producing tools (et_converter, et_generator, SGT, etc.) were using, e.g., `uint64` as the attribute type for `comm_size` when generating binary protobuf ET files. Previously, the ET Feeder had a separate logic to parse this using soft type conversion, so that a uint64 comm_size in protobuf binary would be converted into the `ETFeederNode` class' `int comm_size` member variable. However, since an update in ETFeeder, we now have strong type conversion, the uint64 value was _silently_ ignored. Our resolution was to fix this in the ET producing tool stage, not at the ETFeeder stage or the ASTRA-sim stage


2. Because the new ETFeeder supports `get_other_attr()`, even if ET producers encode a custom attribute (i.e. `involved_dim`), the ASTRA-sim code is able to use the function `ETFeeder.get_other_attr()` to access the `involved_dim` attribute.

**Pull request merged**
