### PR TITLE
Implement Spdlog-Based Logging Framework and Restructure Common Headers and Runs Directory

### PR DESCRIPTION
**Pull request by changhai0109**
## Summary
- Added logging framework 
    - Located at `astra-sim/common/Logging.hh`
    - Using spdlog as backend, which is located at `extern/helper/spdlog`
    - Replaced all cout/cerr in original to loggers.
- Moved APIs/Common.hh to astra-sim/common
    - Moved `astra-sim/system/*API*.hh`, `astra-sim/system/Common.hh` to `astra-sim/common` as these files are shared across layers instead of only used in the system layer.
    - Left soft-link in their original place to maintain backward compatibility
    - Replace `#include` of these headers from `astra-sim/system` to `astra-sim/common`
- Added runs dir to place user's experiments
    - Added `runs` dir at root, which is gitignored
    - Added `runs\example`, which is an example experiment
    - Users can directly pack and share scripts under runs dir, which help people share/reproduce others experiment.

## Test Plan
- Tested with analytical unaware backend
- Test steps:
    - Build: `bash build/astra_analytical/build.sh`
    - Prepare: `cd runs/example/workload && bash ./download.sh`
    - Run: `cd .. && bash ./run.sh`
    
Issue: #126

### CODE REVIEW

**Comment by changhai0109** [comment]
Build fails because -Werror=deprecated-declarations, and that is located in spdlog library and not fixed yet.

**Comment by changhai0109** [comment]
Fixed.

Hi, @beckmabd. Could you please review this PR when you have time? It has been stalled for weeks. Thanks!

**Comment by jinsun-yoo** [comment]
Will resubmit after rebase & cleanup

**Comment by changhai0109** [comment]
Cleaned up. 
Using spdlog_setup to support config user-defined loggers with configuration files.

TODO: replace cout to logger outputs.

**Pull request merged**
